---
apiVersion: v1
kind: Secret
metadata:
  name: rlabs-infra-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/reylabs/rlabs-argo-k3s-manifests

---
apiVersion: v1
data:
  password: Z2hwX05Qc0ZHamc1czhuU1JkcTI0cFJjeUxscnVlUUM2MjBxdkhhdgo=
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL3JleWxhYnMvcmxhYnMtYXJnby1rM3MtbWFuaWZlc3Rz
  username: cm9saW5kcm95Cg==
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: private-repo-creds
  namespace: argocd
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rlabs-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Reylabs Infra Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rlabs-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-applications
    repoURL: 'https://github.com/reylabs/rlabs-argo-k3s-manifests.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
