apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-system
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  source:
    path: apps-manifests/metallb-system
    repoURL: 'https://github.com/reylabs/rlabs-argo-k3s-manifests.git'
    targetRevision: HEAD
  project: rlabs-infra
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true